baseURL = 'https://qiong.me/'
languageCode = 'zh-CN'
title = 'ç©·å…‰è›‹åšå®¢'
theme = "Cactus"

[params]
  colortheme = "classic" # dark, light, white, or classic
  description = "æœ‰äº›äººï¼Œä½ çœ‹è§ä»–æ•´å¤©éƒ½å¼€å¿ƒï¼Œç‡çœŸå¾—åƒä¸ªå°å­©ï¼Œäººäººéƒ½ç¾¡æ…•ä»–ã€‚å…¶å®ï¼Œä»–å°±åƒå‘æ—¥è‘µï¼Œå‘ç€å¤ªé˜³çš„æ­£é¢æ°¸è¿œæ˜åªšï¼Œåœ¨ç…§ä¸åˆ°çš„èƒŒé¢å°†æ‚²ä¼¤æ·±è—ã€‚"
  showAllPostsOnHomePage = false
  postsOnHomePage = 5
  rss = true
  tocInline = true
  showAllPostsArchive = true
  publishDir = "tale.bitbucket.io"
  # css = ["css/custom.css"]


[Permalinks]
  posts = "/posts/:year:month:day"
  

# Main menu which appears below site header.
[[menu.main]]
  name = "ğŸ ä¸»é¡µ"
  url = "/"
  weight = 1

[[menu.main]]
  name = "ğŸ—“å½’æ¡£"
  url = "/posts"
  weight = 2

[[menu.main]]
  name = "ğŸ¤”å…³äº"
  url = "/about"
  weight = 3

[[menu.main]]
  name = "ğŸ”—å‹é“¾"
  url = "/friend"
  weight = 4
  

# Social media links
[[params.social]]
  name = "telegram"
  link = "https://t.me/qiong"

[[params.social]]
  name = "mastodon"
  link = "https://mastodon.social/@qiong"
  
[[params.social]]
  name = "github"
  link = "https://github.com/ColinAZ/blog"

[[params.social]]
  name = "rss"
  link = "/index.xml"

